# Generated by Django 2.2.8 on 2020-01-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='goals',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='subgoals',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='goals',
            name='goal_title',
            field=models.CharField(max_length=128),
        ),
    ]
